name: satay-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - seaborn
  - python >=3.7,<3.9
  - pysam
  - black
  - pip:
      - bump2version
      - pytest
      - pytest-cov
