name: CI Publish

on:
  push:
    tags:
     - "v*.*.*"
     
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install wheel twine
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN}}

  docker:
      runs-on: ubuntu-latest
      steps:
        - name: Set environment variable
          run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
        - name: Check Out Repo 
          uses: actions/checkout@v2          
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/satay:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/satay:${{ env.RELEASE_VERSION }}
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
