name: CI Test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  first_check:
    name: first code check / python-3.8 / ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python info
        run: |
          which python
          python --version
      - name: Build package and create dev environment
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Test with coverage
        run: |
          pytest --cov= --cov-report term --cov-report xml --junitxml=xunit-result.xml          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          
          
          
         

